

# This is the general fallback rule for your React single-page app.
# It makes sure that refreshing on pages like /login works correctly.
# It must come second.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200